### ISSUE TITLE
SyntaxError: unterminated string literal in install.py

### ISSUE THREAD

**Issue by AswinWhiteHat** [gotr00t0day/spyhunt#11]
Description:
When attempting to run sudo python3 install.py, I encountered a SyntaxError in the install.py file. Below is the error message:

File "/home/aswin/Desktop/av/spyhunt/install.py", line 147
    commands("go install github.com/tomnomnom/assetfinder@latest | cd {}/go/bin | sudo mv {}/go/bin/assetfinder /usr/local/bin".format(home, home))")
                                                                                                                                                   ^
SyntaxError: unterminated string literal (detected at line 147)

Steps to Reproduce:-
Navigate to the directory containing the install.py script.
Run sudo python3 install.py

Expected Behavior:
The install.py script should run without any syntax errors.

Actual Behavior:
The install.py script throws a SyntaxError at line 147, stating that there is an unterminated string literal.

**Comment by mayormaynotbeano** [comment]
Hi! The author added this 12 hours ago, but made a slight mistake.
The error is given because of the closing parenthesis and the quotation, which are not needed.
Remove the unnecessary closing parenthesis ) to properly terminate the string literal and remove the extra double quotation mark " at the end of the line. That should fix the problem. Here is the previous and fixed lines:

Previous:
`commands("go install github.com/tomnomnom/assetfinder@latest | cd {}/go/bin | sudo mv {}/go/bin/assetfinder /usr/local/bin".format(home, home))")`

New:
`commands("go install github.com/tomnomnom/assetfinder@latest | cd {}/go/bin | sudo mv {}/go/bin/assetfinder /usr/local/bin".format(home, home))
`
